--- pdns-recursor-3.5.3/Makefile.orig	2014-01-25 16:03:01.530273485 +0100
+++ pdns-recursor-3.5.3/Makefile	2014-01-25 19:11:15.000000000 +0100
@@ -78,10 +78,8 @@
 	mv rec_control $(DESTDIR)/$(BINDIR)
 	strip $(DESTDIR)/$(BINDIR)/rec_control
 	-mkdir -p $(DESTDIR)/$(CONFIGDIR)
-	$(DESTDIR)/$(SBINDIR)/pdns_recursor --config > $(DESTDIR)/$(CONFIGDIR)/recursor.conf-dist
-	-mkdir -p $(DESTDIR)/usr/share/man/man1
-	cp pdns_recursor.1 rec_control.1 $(DESTDIR)/usr/share/man/man1
-	$(OS_SPECIFIC_INSTALL)	
+	-mkdir -p $(DESTDIR)/usr/man/man1
+	cp pdns_recursor.1 rec_control.1 $(DESTDIR)/usr/man/man1
 
 clean: binclean
 	-rm -f dep *~ *.gcda *.gcno optional/*.gcda optional/*.gcno
