#!/bin/sh
#
# /etc/rc.d/pdns-recursor: start/stop PowerDNS Recursor daemon
#

case $1 in
start)
	/usr/sbin/pdns_recursor --daemon=yes &>/dev/null
	;;
stop)
	/usr/bin/rec_control quit &>/dev/null
	;;
restart)
	$0 stop
	sleep 2
	$0 start
	;;
*)
	echo "usage: $0 [start|stop|restart]"
	;;
esac

# End of file
 