#!/bin/sh

source /u01/app/oracle/product/11.2.0/xe/bin/oracle_env.sh

availphymem=`cat /proc/meminfo | grep '^MemTotal' | awk '{print $2}'`
availphymem=`echo $availphymem / 1024 | bc`
memory_target=`echo 0.40 \* $availphymem | bc | sed "s/\..*//"`
if [ $memory_target -gt 1024 ];
then
	memory_target=`echo 1024 \* 1048576 | bc`
else
	memory_target=`echo $memory_target \* 1048576 | bc`
fi

/bin/sed -i "s/%memory_target%/$memory_target/g" /u01/app/oracle/product/11.2.0/xe/config/scripts/init.ora
/bin/sed -i "s/%memory_target%/$memory_target/g" /u01/app/oracle/product/11.2.0/xe/config/scripts/initXETemp.ora

/etc/rc.d/oracle-shm start
/etc/rc.d/oracle-xe configure

echo
echo "############################################################"
echo "Add \"source /u01/app/oracle/product/11.2.0/xe/bin/oracle_env.sh\" to your \"/etc/profile\"."
echo
echo "Add your user to the \"dba\" group in order to use the oracle tools."
echo "############################################################"
echo
